### ISSUE TITLE
The SEED_BRANCH variable does not convert the / for a custom naming convention

### ISSUE THREAD

**Issue by dcoraboeuf** [jenkinsci/seed-plugin#11]
Using the following Seed configuration:

```yaml
strategies:
        - id: xxx
          seed-expression: "${PROJECT}/${PROJECT}_GENERATOR"
          branch-seed-expression: "${PROJECT}/${PROJECT}_*/${PROJECT}_*_GENERATOR"
          branch-start-expression: "${PROJECT}/${PROJECT}_*/${PROJECT}_*_010_BUILD"
          branch-name-expression: "${BRANCH}"
```

when using `release/1.0` as a branch, we expect `RELEASE_1.0` as a value for `SEED_BRANCH` but get `RELEASE/1.0` instead, causing problems when generating jobs.
