### ISSUE TITLE
Cannot trigger pipeline when using a custom naming convention

### ISSUE THREAD

**Issue by dcoraboeuf** [jenkinsci/seed-plugin#17]
Given the following configuration:

```yaml
strategies:
  - id: ci
    branch-start-expression: "${project}/${project}-*/${project}-*-ci"
classes:
    - id: my-class
      branch-strategy: ci
```

If the project `p` uses the `my-class` class, then firing the following event:

```bash
curl -X POST "http://192.168.99.101:32769/seed-http/commit?project=p&branch=master&commit=100"
```

raises the following error:

```
{"status":"ERROR","message":"Cannot find job in context [/p/p-master] with path [p-master-build]"}
```

The `p-master-ci` build should have been fired instead.
